server:
  port: 8080
spring:
  application:
    name: eureka
eureka:
  instance:
    prefer-ip-address : true
  client:
    service-url:
      fetch-registry: false
      defaultZone: http://192.168.117.199:8080/eureka/
      register-with-eureka: true
  server:
    enable-self-preservation: true #自我保护开发时为false,发布为true
    eviction-interval-timer-in-ms: 10000
    peer-node-read-timeout-ms: 10000
